# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('slastname', models.CharField(max_length=30)),
                ('smarks', models.IntegerField()),
                ('sclass', models.CharField(max_length=30)),
            ],
        ),
    ]
